modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="redstonesnorting"
version="1.0.0"
displayName="SnortRedstone"
credits="https://github.com/GamingBurber/SnortableRedstone"
displayURL="https://mcreator.net"
authors="GamingBurber"
description='''
SNORT REDSTONE!!!
'''

[[dependencies.redstonesnorting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




